[package]
name = "fvrs-plugin-api"
version = "0.1.0"
edition = "2021"
authors = ["FVRS Team"]
license = "MIT OR Apache-2.0"
description = "Plugin API for FVRS"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
libloading = { workspace = true } 