[package]
name = "fvrs-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[[bin]]
name = "fvrs"
path = "src/main.rs"

[dependencies]
fvrs-core = { workspace = true }
tokio = { workspace = true }
